favicon: /favicon.ico

menu:
  home:
    href: ''
    icon: home
  archives:
    href: archives
    icon: archive
  categories:
    href: categories
    icon: th
  tags:
    href: tags
    icon: tags
  about:
    href: http://xcatliu.com
    icon: user
    align: right

sidebar:
  title: true
  subtitle: false
  avatar: /assets/about/xcatliu_512.png
  description: true
  social:
    GitHub: https://github.com/xcatliu
    Twitter: https://twitter.com/xcatliu
    Gmail: mailto:xcatliu@gmail.com
  links:
    康瑞部落: http://www.kangry.net/blog/
    创造狮: http://chuangzaoshi.com/
    "James Pan's Blog": https://blog.jamespan.me/
    搞机男: http://www.gaojinan.com/
    More: /links
  toc: true

disqus_shortname: xcatliu

# Google Analytics
google_analytics: UA-45256157-6

since: 2012
